### ISSUE TITLE
Refactor construction of file paths in blocks.py

### ISSUE THREAD

**Issue by brendancol** [makepath/makestack#21]
I got the following error:

```bash
(base) ➜  ~ conda activate test_project_999
(test_project_999) ➜  ~ pip install makestack
Collecting makestack
  Using cached makestack-0.1-py3-none-any.whl
Collecting qprompt==0.16.3
  Using cached qprompt-0.16.3-py3-none-any.whl
Collecting click-plugins>=1.1.1
  Using cached click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting click>=8.1.3
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting iterfzf
  Using cached iterfzf-0.5.0.20.0-py2.py3-none-macosx_10_10_intel.macosx_10_10_x86_64.macosx_10_11_intel.macosx_10_11_x86_64.macosx_10_12_intel.macosx_10_12_x86_64.whl (1.1 MB)
Requirement already satisfied: setuptools in ./miniconda3/envs/test_project_999/lib/python3.10/site-packages (from iterfzf->qprompt==0.16.3->makestack) (65.6.3)
Installing collected packages: iterfzf, click, qprompt, click-plugins, makestack
Successfully installed click-8.1.3 click-plugins-1.1.1 iterfzf-0.5.0.20.0 makestack-0.1 qprompt-0.16.3
(test_project_999) ➜  ~ which makestack
/Users/brendan/miniconda3/envs/test_project_999/bin/makestack
(test_project_999) ➜  ~ makestack startproject --name test_project_999 --directory .
(test_project_999) ➜  ~ rm -rf test_project_999
(test_project_999) ➜  ~ makestack startproject --name test_project_999 --directory .
[!] Creating the project folder. DONE.
-----------------------------------------------------------------
[?] Add Django to the environment?: y
[?] Add GeoServer to the environment?: n
[?] Add Mapshader to the environment?: n
[?] Add Nginx to the environment?: y
[?] Add Redis to the environment?: y
[?] Add Celery to the environment?: y
[?] Add React to the environment?: y
[?] Add Terraform to the environment?: y
[?] Add Sphinx to the environment?: n
-----------------------------------------------------------------
[INFO] Starting to set up the project environment.
[!] Setting up General Files... Traceback (most recent call last):
  File "/Users/brendan/miniconda3/envs/test_project_999/bin/makestack", line 8, in <module>
    sys.exit(main())
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/makestack/startproject.py", line 63, in startproject
    general.set_up()
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/makestack/blocks.py", line 18, in set_up
    qprompt.status(f"Setting up {self.name}...", self._set_up)
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/qprompt.py", line 636, in status
    return decor(func)(*fargs, **fkrgs)
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/qprompt.py", line 623, in wrapper
    result = func(*args, **krgs)
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/makestack/blocks.py", line 81, in _set_up
    self._copy_base_folder()
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/site-packages/makestack/blocks.py", line 59, in _copy_base_folder
    shutil.copytree(source, destination, dirs_exist_ok=True)
  File "/Users/brendan/miniconda3/envs/test_project_999/lib/python3.10/shutil.py", line 556, in copytree
    with os.scandir(src) as itr:
FileNotFoundError: [Errno 2] No such file or directory: 'makestack/data/general'
```

**Comment by brendancol** [comment]
Let's contruct those paths like:
```python
class BaseBlock():
    def __init__(self):
        self.here = os.path.dirname(os.path.abspath(__file__))

class Block(BaseBlock):
    def _copy_..():
        source = os.path.join(self.here, 'data', 'docker', '...')
```
